### ISSUE TITLE
Bug in null_suspicious_dob_std function

### ISSUE THREAD

**Issue by lauratraceymoj** [moj-analytical-services/splink_data_standardisation#15]
In defining the function it takes a variable `dob_col` but function code is written using `dob_std` which is the default value rather than the variable name. This means the function errors if user is trying to use a column with a different name to the default.

[Lines 57 - 59 ](https://github.com/moj-analytical-services/splink_data_standardisation/blob/master/splink_data_standardisation/date_of_birth.py#L57-L59) needs changing to use `dob_col` instead of `dob_std`

**Comment by mamonu** [comment]
closed by #16
